<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Functions (Need)</span></div>

## 1 User defined functions

### 1.1 Named functions that return

In [8]:
def greeting(name):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    else:
        return f'Hello {name}!'

In [7]:
greeting("Super Man")

'Hello Super Man!'

In [9]:
print(greeting(name='Super Man'))

Hello Super Man!


In [15]:
import numpy as np
def basic_stats(numbers):
    np_numbers=np.array(numbers)
    return np_numbers.min(), np_numbers.max(), np_numbers.mean(

In [17]:
list_min, list_max, list_mean = basic_stats([1, 2, 3, 4, 5])

### 1.2 Named functions that don’t return

### 1.3 Anonymous functions

In [ ]:
my_short_function = lambda name: f"Hello {name}!"
my_short_function(name="Super Man")

In [22]:
numbers=[[9, 0, 10],
         [8, 1, 11],
         [7, 2, 12],
         [6, 3, 13],
         [5, 4, 14],
         [4, 5, 15],
         [3, 6, 16],
         [2, 7, 17],
         [1, 8, 18],
         [0, 9, 19]]

sorted(numbers)                         # Sort by comparing the default key 
              

[[0, 9, 19],
 [1, 8, 18],
 [2, 7, 17],
 [3, 6, 16],
 [4, 5, 15],
 [5, 4, 14],
 [6, 3, 13],
 [7, 2, 12],
 [8, 1, 11],
 [9, 0, 10]]

In [23]:
sorted(numbers, key=lambda x: x[1])     # Sort by comparing a custom key
                                        # that uses the 2nd element

[[9, 0, 10],
 [8, 1, 11],
 [7, 2, 12],
 [6, 3, 13],
 [5, 4, 14],
 [4, 5, 15],
 [3, 6, 16],
 [2, 7, 17],
 [1, 8, 18],
 [0, 9, 19]]

In [24]:
sorted(numbers, key=lambda x: sum(x))   # Sort by comparing a custom key
                                        # that uses the sum of the elements

[[9, 0, 10],
 [8, 1, 11],
 [7, 2, 12],
 [6, 3, 13],
 [5, 4, 14],
 [4, 5, 15],
 [3, 6, 16],
 [2, 7, 17],
 [1, 8, 18],
 [0, 9, 19]]

### 1.4 Optional arguments

In [29]:
def greeting(name='no one'):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    else:
        return f'Hello {name}!'

In [30]:
greeting()

'Hello no one!'

In [31]:
print('I', 'am', 'Batman!')                 # Just for comparison
#> I am Batman!
print('I', 'am', 'Batman!', sep='---')  
#> I---am---Batman!

I am Batman!
I---am---Batman!


## 2 The importance of functions?

### 2.1 An argument for functions

In [ ]:

# Your code here


### 2.2 A word of caution

In [ ]:

# Your code here


## Exercise 1 :  Do you know why?

In [39]:
def greeting(name):
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    return f'Hello {name}!'
greeting('Batman')

'Hello Batman! So, nice to meet you!'

if statement only checks if name is equal to 'Batman'. without the else statement, it does not affect the code, as the code will always return a string, either the one definined in if statement or the one returned by return statement outside of the if statement

## Exercise 2 :  Calculator functions

In [40]:
import numpy as np

def add(x,y):
    x=np.array(x) 
    y=np.array(y)
    return x+y

x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])

add(x,y)

array([100, 100, 100, 100, 100])

In [44]:
import numpy as np

def subtract(x,y):
    x=np.array(x) 
    y=np.array(y)
    return x-y

x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])
subtract(x,y)

array([-28, -32, -12,  52, -46])

In [45]:
import numpy as np

def multiply(x,y):
    x=np.array(x) 
    y=np.array(y)
    return x*y

x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])

multiply(x,y)

array([2304, 2244, 2464, 1824, 1971])

In [48]:
np.any(y==0)

False

In [46]:
import numpy as np

def divide(x,y):
    x=np.array(x) 
    y=np.array(y)
    return x/y

x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])

divide(x,y)

array([0.5625    , 0.51515152, 0.78571429, 3.16666667, 0.36986301])

## Exercise 3 :  max_info() with NumPy

In [56]:
import numpy as np

numbers = [40, 27, 83, 44, 74, 51, 76, 77, 10, 49]
def max_info(numbers):
    numbers=np.array(numbers)
    return np.max(numbers)


In [57]:
np.max(numbers)

83

In [59]:
np.argmax(numbers)

2