<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Functions (Good)</span></div>

## 1 Check, balances and contingencies

### 1.1 assert

In [6]:
x = 10
assert x >= 0, "x is becoming negative!"

### 1.2 try-except

In [7]:
number=input("Give me a number and I will calculate its square.")
square=int(number)**2              # Convert English to number
print(f'The square of {number} is {square}!')

Give me a number and I will calculate its square.7
The square of 7 is 49!


In [12]:
try:
    number=input("Give me a number and I will calculate its square.")
    square=int(number)**2
    print(f'The square of {number} is {square}!')
except:
    print(f"Oh oh! I cannot square {number}!")

Give me a number and I will calculate its square.uhafjd
Oh oh! I cannot square uhafjd!


## 2 Some loose ends

### 2.1 Positional, keyword and default arguments

In [14]:
def funny_add(a, b, c=1):
    return a + 10*b + 100*c
funny_add(1, 2)           # Two positional, 1 default
#> 121
funny_add(1, 2, 3)        # Three positional
#> 321
funny_add(a=1, b=2)       # Two keyword, 1 default
#> 121
funny_add(c=3, b=1, a=2)  # Three keyword
#> 312
funny_add(1, c=3, b=2)    # One positional, 2 keyword
#> 321

321

### 2.2 Docstrings

In [15]:
def funny_add(a, b, c=1):
    '''
    A test function to demonstrate how 
    positional, keyword and default arguments 
    work.
    '''
    return a + 10*b + 100*c
help(funny_add)

Help on function funny_add in module __main__:

funny_add(a, b, c=1)
    A test function to demonstrate how 
    positional, keyword and default arguments 
    work.



### 2.3 Function are first class citizens

In [ ]:
def my_function(angle, trig_function):
        return trig_function(angle)

# Let's use the function
my_function(np.pi/2, np.sin)        
#> 1.0
my_function(np.pi/2, np.cos)        
#> 6.123233995736766e-17
my_function(np.pi/2, lambda x: np.cos(2*x))  
#> -1.0

### 2.4 More unpacking

In [18]:
x, y, z = [1, 2, 3]
print(x, y, z)

1 2 3


In [20]:
import numpy as np
x, y, z = np.array([1, 2, 3])
print(x, y, z)

1 2 3


In [21]:
x, *y, z = np.array([1, 2, 3, 4, 5])
print(x, y, z)

1 [2, 3, 4] 5


In [22]:
x, *_, y = [1, 2, 3, 4, 5]
print(x, y)

1 5


## Exercise 1 :  A better calculator I

In [23]:
import numpy as np
x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])
def add(x,y):
    x=np.array(x) 
    y=np.array(y)
    return x+y
add(x,y)

array([100, 100, 100, 100, 100])

In [24]:
def subtract(x,y):
    x=np.array(x) 
    y=np.array(y)
    return x-y

x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])
subtract(x,y)

array([-28, -32, -12,  52, -46])

In [25]:
def multiply(x,y):
    x=np.array(x) 
    y=np.array(y)
    return x*y

x=np.array([36, 34, 44, 76, 27])
multiply(x,y)

array([2304, 2244, 2464, 1824, 1971])

In [31]:
import numpy as np

def divide(x,y):
    x=np.array(x) 
    y=np.array(y)
    assert (y!=0).all(), "error"
    return x/y

x=np.array([36, 34, 44, 76, 27])
y=np.array([64, 66, 56, 24, 73])
divide(x, y)

array([0.5625    , 0.51515152, 0.78571429, 3.16666667, 0.36986301])

## Exercise 2 :  A better calculator II

In [28]:
try:
    divide=x/y
    print(devide)
except:
    print('error')

error
