<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

## 1 Lists, Arrays & Dictionaries

### 1.1 Let’s compare

In [ ]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])


### 1.2 Accessing data from a list (or array)

In [3]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]
print(py_real_names[0])
print(py_super_names[0])

Natasha Romanoff
Black Widow


### 1.3 Accessing data from a dictionary

In [5]:
py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]
print(py_real_names[0])
print(py_super_names[0])
print(py_super_names[2])    # Forward indexing 
                            # We need to know the size 
                            # beforehand for this to work.
print(py_super_names[-1])   # Reverse indexing

Natasha Romanoff
Black Widow
Doctor Strange
Doctor Strange


### 1.4 Higher dimensional lists

In [10]:
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }
print(superhero_info["Natasha Romanoff"])
superhero_info.keys()
superhero_info.values()
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]

Black Widow


## 2 Lists vs. Arrays

### 2.1 Size

In [18]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]
len(py_list_2d)

10

In [21]:
import numpy as np
np_array_2d = np.array(py_list_2d)
len(np_array_2d)

10

### 2.2 Arrays are fussy about type

In [22]:
py_list = [1, 1.5, 'A']
np.array(py_list)

array(['1', '1.5', 'A'], dtype='<U32')

### 2.3 Adding a number

In [24]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         
np_array + 10

array([11, 12, 13, 14, 15])

### 2.4 Adding another list

In [27]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)
py_list_1 + py_list_2
np_array_1 + np_array_2

array([11, 22, 33, 44, 55])

### 2.5 Multiplying by a Number

In [29]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         
py_list*2
np_array*2

array([ 2,  4,  6,  8, 10])

### 2.6 Squaring

In [30]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)
np_array**2


array([ 1,  4,  9, 16, 25])

### 2.7 Asking questions

In [33]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         
py_list == 3     # Works, but what IS the question?
np_array == 3  
np_array > 3  

array([False, False, False,  True,  True])

### 2.8 Mathematics

In [41]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         
sum(py_list)     # sum() is a base Python function
max(py_list)     # max() is a base Python function
min(py_list)     # min() is a base Python function
np_array.sum()
np_array.mean()
np_array.max()
np_array.min()

1

## Exercise 1 :  Total recall?

_1. both can use to store data, both allow indexing
2. lists cannot manage arithmetic operations while arrays can, list no need import numpy but array need
3. dictionary is one type of data structure in Python, but not the only one. It is a collection of mutable key-value pairs. The key is used to access the stored value._

## Exercise 2 :  Index me

In [1]:
py_list = ["a1", "b2", "c3", "d4", "e5", "f6", "g7", "h8", "i9", "j10"]
                    # Prints 'a1'
                    # Prints 'c3'
                    # Prints 'e5'
                    # Prints 'g7'
py_list = ["a1", "b2", "c3", "d4", "e5", "f6", "g7", "h8", "i9", "j10"]
                 
print(py_list[::2])

['a1', 'c3', 'e5', 'g7', 'i9']


## Exercise 3 :  Capitalise Heros

In [49]:
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }

superhero_info['Tony Stark'] = superhero_info['Tony Stark'].upper()
superhero_info['Natasha Romanoff'] = superhero_info['Natasha Romanoff'].upper()
superhero_info['Stephen Strange'] = superhero_info['Stephen Strange'].upper()
print(superhero_info)

{'Natasha Romanoff': 'BLACK WIDOW', 'Tony Stark': 'IRON MAN', 'Stephen Strange': 'DOCTOR STRANGE'}


## Exercise 4 :  How many ones

In [2]:
Numbers=[45, 60, 1, 30, 96, 1, 96, 57, 16, 1,
        99, 62, 86, 43, 42, 60, 59, 1, 1, 35,
        83, 47, 34, 28, 68, 23, 22, 92, 1, 79,
        1, 29, 94, 72, 46, 47, 1, 74, 32, 20,
        8, 37, 35, 1, 89, 29, 86, 19, 43, 61]                  
import numpy as np
np_array=np.array(Numbers)

(np_array==1).sum()

9